{% extends 'layout.html.twig' %}

{% block content_title %}Fatal Error
{% endblock content_title %}
{% block page_title %}
	<span uk-icon="icon: warning; ratio: 2" class="uk-text-danger"></span> {{ exception.getMessage() }}
	<div class="uk-text-meta uk-margin-medium-left">Uncaught Exception</div>
{% endblock page_title %}

{% block content %}
	<div class="uk-section uk-light">
		<div class="uk-container">

			<ul uk-accordion>
				<li class="uk-close">
					<a class="uk-accordion-title" href="#">BadMethodCallException</a>
					<small class="uk-text-danger">{{ exception_class }}</small>
					<div class="uk-accordion-content">
						<p>
							<div>Stack Trace <span class="uk-badge uk-badge-danger uk-text-warning uk-text-bolder">{{ exception.getTrace()|length }} <span></div>
							<ul class="uk-list uk-list-divider">
								{% for index, trace in exception.getTrace() %}
									{% if trace.class !='' %}
										<li>

											#{{ index }} {{ trace.file }} (<span class="uk-text-danger">{{ trace.line }}</span>) : {{ trace.class }}{{ trace.type }}{{ trace.function }}<span class="uk-text-success">({{ trace.args }})</span>

										</li>
									{% endif %}
								{% endfor %}
							</ul>
						</p>
						<p>Main error was thrown in:
							{{ exception.getFile() }}. On line <span class="uk-text-danger uk-text-bolder">({{ exception.getLine() }})</span></p>
					</div>
				</li>
			</ul>
		</div>
	</div>

{% endblock content %}
